-- =====================================================================
--  預設項目定義（與原 index.html 內建預設一致）
--  The application also loads these automatically on first start when
--  db.seedDefaultsIfEmpty=true and DEF_TASK is empty.
-- =====================================================================

-- ---------- 批次作業 A1~A32 ----------
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A1', 1,'批次前置作業 (JST0000D)','business_day','17:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A2', 2,'主機前IC作業','daily','19:00','evening',1,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A3', 3,'分行關機時間','daily','20:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A4', 4,'會計月底批次作業結束時間','monthly_first_business','09:00','day',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A5', 5,'主機批次正式開始 (JBATSTRD)','daily','20:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A6', 6,'主機入扣帳結束 (JPU8500D/CPU6620D)','daily','04:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A7', 7,'主機批次全部結束 (JAM8600D)','daily','05:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A8', 8,'主機後IC作業','daily','05:00','night',1,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A9', 9,'Volume Backup作業 ⚡跨班','daily','05:00','cross',1,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A10',10,'JOF300FD (分行批次簽退)','business_day','22:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A11',11,'JON3500D (檢查分行關機)','business_day','22:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A12',12,'JBC3900D (次日帳)','business_day','22:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A13',13,'JMI120XD (各業務交易餘額)','business_day','22:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A14',14,'JAM5200D (ATM扣帳)','business_day','22:00','evening',0,'ATM筆數',1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A15',15,'CBC3500D (批次開始換日)','daily','00:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A16',16,'CBC3900D (批次結束換日)','daily','01:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A17',17,'CBC5000D (主機批次次日帳)','daily','01:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A18',18,'JBM5200D (託收明細檔)','business_day','02:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A19',19,'CPU6110D (台大/軍公教薪資)','monthly_first','02:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A20',20,'CFD6000D (領息次日帳)','daily','02:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A21',21,'CMB6100D (綜存轉定存)','daily','02:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A22',22,'JLA6100/6200D (放款扣款)','business_day','03:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A23',23,'JCK6100~6300D (MICR扣帳)','business_day','03:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A24',24,'JCR6200D (信用卡扣帳)','business_day','03:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A25',25,'JFN6300D (基金扣帳)','business_day','03:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A26',26,'JVD6000D (悠遊金融卡)','business_day','04:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A27',27,'CPU6310D (公共事業代扣)','daily','04:00','night',0,'STEP筆數',1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A28',28,'EDI批次—前端作業','daily','18:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A29',29,'EDI—JCK530FD後(台朔)','daily','01:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A30',30,'EDI—JED660FD後-關貿','daily','04:00','night',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A31',31,'大陸分行批次作業','daily','20:00','evening',0,NULL,1);
INSERT INTO DEF_TASK (CODE,SEQ,NAME,SCHEDULE,PLANNED_START,SHIFT,HAS_END,QTY_LABEL,ENABLED) VALUES ('A32',32,'EOI及EDI系統閉啟作業','weekly_sunday','22:00','evening',0,NULL,1);

-- ---------- 系統設備檢查 ----------
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('branchNet',1,'分行網路設備檢查','status','night','','正常|假日不執行|異常',1);
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('dms1',2,'DMS 第1次','dms','day','',NULL,1);
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('dms2',3,'DMS 第2次','dms','evening','',NULL,1);
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('dms3',4,'DMS 第3次','dms','night','',NULL,1);
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('imsClose',5,'PROD IMS 開始關閉','ims','day','',NULL,1);
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('imsStart',6,'PROD IMS 啟動完畢','ims','day','',NULL,1);
INSERT INTO DEF_EQUIP (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,STATUS_OPTIONS,ENABLED) VALUES ('creditCard',7,'PROD 信用卡部通知','text','night','',NULL,0);

-- ---------- 三班檢查 ----------
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_portal', 1,'PORTAL檢查','portal','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_phone',  2,'電話語音','general','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_monitor',3,'監控檢查','general','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_light',  4,'設備燈號檢查','general','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_cabinet',5,'機櫃檢查','cabinet','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_psdb',   6,'PSDB換KEY','general','day','',1,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_cbond',  7,'央行公債簽到','general','day','',1,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_sms',    8,'SMS USAGE','sms','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('day_rmf',    9,'TSO RMF','rmf','day','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('eve_portal',10,'PORTAL檢查','portal','evening','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('eve_phone', 11,'電話語音','general','evening','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('eve_light', 12,'設備燈號檢查','general','evening','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('eve_cabinet',13,'機櫃檢查','cabinet','evening','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_portal',14,'PORTAL檢查','portal','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_phone', 15,'電話語音','general','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_light', 16,'設備燈號檢查','general','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_cabinet',17,'機櫃檢查','cabinet','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_nbu',   18,'NBU/PPDM備份','general','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_nw',    19,'Networker備份','general','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_nwtc',  20,'Networker台中分儲','general','night','',0,1);
INSERT INTO DEF_CHECK (DEF_ID,SEQ,NAME,ITEM_TYPE,SHIFT,CHECK_TIME,HOLIDAY_SKIP,ENABLED) VALUES ('ngt_as400', 21,'AS400備份','general','night','',0,1);
